"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
    black = '#262B44'
    blue = '#4B95E9'
    green = '#59C9A5'
    orange = '#F07623'
    red = '#D81E5B'
    white = '#e6e9ef'
    yellow = '#F3AE35'
    muave = '#8839ef'
    lavender = '#7287fd'
    sapphire = '#209fb5'
    surface0 = '#ccd0da'

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        leading_diamond = ''
        trailing_diamond = ''
        foreground = 'p:white'
        background = 'blue'
        type = 'path'
        style = 'diamond'
        template = '  {{ path .Path .Location }} '

        [blocks.segments.properties]
            style = 'full'

    [[blocks.segments]]
        template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
        leading_diamond = '<transparent,background></>'
        trailing_diamond = ''
        foreground = 'p:black'
        background = 'p:green'
        type = 'git'
        style = 'diamond'

        [blocks.segments.properties]
            branch_max_length = 25
            fetch_status = true
            fetch_upstream_icon = false
            branch_icon = ' '

    [[blocks.segments]]
        leading_diamond = '<transparent,background></>'
        trailing_diamond = ''
        template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
        foreground = 'p:black'
        background = 'p:surface0'
        type = 'status'
        style = 'diamond'
        foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
#background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

        [blocks.segments.properties]
            always_enabled = true


[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        template = ' 󱞪'
        foreground = 'black'
        background = 'transparent'
        type = 'text'
        style = 'plain'

        [blocks.segments.properties]
            always_enabled = true

[[blocks]]
    type = 'rprompt'

    [[blocks.segments]]
        type = "executiontime"
        style = "plain"
        template = " {{ .FormattedMs }} "

        [blocks.segments.properties]
            threshold = 500
            style = "austin"
            always_enabled = true

    [[blocks.segments]]
        template = '{{ .CurrentDate | date "15:04:05" }}'
        foreground = 'white'
        background = 'transparent'
        type = 'time'
        style = 'plain'
        overflow = 'hide'

[secondary_prompt]
    template = ' … '
    foreground = 'black'
    background = 'transparent'
